services:
  postgres:
    image: postgres
    container_name: postgres_logging
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./pg_log/:/var/log/postgres
    command:
      - -c
      - log_destination=stderr
      - -c
      - logging_collector=on
      - -c
      - log_directory=/var/log/postgres
    networks:
      - backend
  app:
    container_name: flask_application
    build: .
    ports:
      - "5000:5000"
    networks:
      - backend
networks:
  backend:
    driver: bridge