"""Add Column 'patronymic' to Users table.

Revision ID: 28df82c9df9e
Revises: 6dd44a3a8963
Create Date: 2025-08-18 05:34:35.498539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28df82c9df9e'
down_revision: Union[str, Sequence[str], None] = 'ce77f3413a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('patronymic', sa.String(length=75), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'patronymic')
    # ### end Alembic commands ###
