"""Add Column 'surname' to Users table. Restore column 'has sale'

Revision ID: 6dd44a3a8963
Revises: 5442411e974e
Create Date: 2025-08-18 05:33:53.162736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd44a3a8963'
down_revision: Union[str, Sequence[str], None] = '5442411e974e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(length=75), nullable=True))
    op.add_column('users', sa.Column('has_sale', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_sale')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
