FROM debian:stretch

FROM test_app AS base

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://archive.debian.org/debian stretch main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until

WORKDIR /app

COPY requirements.txt /app/

RUN apt-get update && apt-get install -y htop procps

RUN python -m pip install --no-cache-dir -r /app/requirements.txt

